# Generated by Django 4.2.7 on 2026-05-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_employee_time_off'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeetimeoff',
            new_name='employee_ti_employe_bfff47_idx',
            old_name='employee_tim_employe_f43e07_idx',
        ),
    ]
