# Generated by Django 4.2.7 on 2026-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_contact_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLCompanyAuth',
            fields=[
                ('company_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('expires_in', models.IntegerField(default=0)),
                ('scope', models.TextField(blank=True, default='')),
                ('user_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
