# Generated by Django 4.2.7 on 2026-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_ghlcompanyauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=20)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('automatic_mobile_app_invite', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField()),
                ('domain', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ghl_api_locations',
            },
        ),
    ]
