# Generated by Django 4.2.7 on 2026-05-15 15:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0030_alter_appointment_job_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpricing',
            name='yes_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed amount (e.g. 12.00) or percentage for percent-of-total (e.g. 10 for 10%)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_house_size_management_tool',
            field=models.BooleanField(default=False, help_text='Grants access to the house size management tool for this user.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_location_management_tool',
            field=models.BooleanField(default=False, help_text='Grants access to the location management tool for this user.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_service_management_tool',
            field=models.BooleanField(default=False, help_text='Grants access to the service management tool for this user.'),
        ),
    ]
