# Generated by Django 4.2.7 on 2026-06-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0031_alter_questionpricing_yes_value_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
