# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0032_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ghl_company_id',
            field=models.CharField(
                blank=True,
                help_text='GHL company id for agency users (limits cross-company access).',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='ghl_location_ids',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='GHL roles.locationIds when restrictSubAccount is enabled for agency users.',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='ghl_restrict_sub_account',
            field=models.BooleanField(
                default=False,
                help_text='When True, agency user access is limited to ghl_location_ids.',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='ghl_user_type',
            field=models.CharField(
                blank=True,
                help_text='GHL user type from sync: agency or account.',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('manager', 'Manager'),
                    ('supervisor', 'Supervisor'),
                    ('agency', 'Agency'),
                    ('worker', 'Worker'),
                ],
                default='worker',
                max_length=20,
            ),
        ),
    ]
