# Generated by Django 4.2.7 on 2026-05-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0031_customersubmission_persisted_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubmission',
            name='is_persisted_snapshot',
        ),
        migrations.RemoveField(
            model_name='customersubmission',
            name='source_submission',
        ),
    ]
