# Generated by Django 4.2.7 on 2026-05-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0032_remove_customersubmission_is_persisted_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubmission',
            name='is_persisted_snapshot',
            field=models.BooleanField(blank=True, default=False, help_text='When True, this submission is an immutable copy of the original proposal.', null=True),
        ),
        migrations.AddField(
            model_name='customersubmission',
            name='source_submission',
            field=models.OneToOneField(blank=True, help_text='Working submission this snapshot was copied from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persisted_snapshot', to='quote_app.customersubmission'),
        ),
    ]
